spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DATABASE}?ApplicationName=istoepousada
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver