spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DATABASE}
    username: ${USER_DATABASE}
    password: ${PASSWORD_DATABASE}
    driver-class-name: org.postgresql.Driver