spring:
  threads:
    virtual:
      enabled: true

  application:
    name: istoepousada

  jackson:
    time-zone: America/Sao_Paulo

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

springdoc:
  api-docs:
    path: /api-docs

server:
  port: ${PORT:8080}
